### ISSUE TITLE
article_checker 长时间工作后不再能从队列中取出项目

### ISSUE THREAD

**Issue by MamaShip** [MamaShip/Observer#90]
原因不明。推测跟 #73 的修改有关。

具体表现（bug发生时是7月2号，6月29号之前使用alpha版本，未修复 queue get error冲日志的bug #71）：
```
twisted@wx:/var/wx/Observer/src$ cat article_checker.log 
2020-06-29 12:05:22,348 - article_checker - ERROR - checker queue get error
2020-06-29 12:05:29,352 - article_checker - ERROR - checker queue get error
2020-06-29 12:05:36,356 - article_checker - ERROR - checker queue get error
2020-06-29 12:05:43,360 - article_checker - ERROR - checker queue get error
2020-06-29 12:05:50,368 - article_checker - ERROR - checker queue get error
2020-06-29 12:05:57,373 - article_checker - ERROR - checker queue get error
twisted@wx:/var/wx/Observer/src$
```
（↑ 未记录日志）

使用管理员命令查询可见：
```
自己的大腿:
admin-status

时间从来不回答:
现有3条记录观察中
状态1的有1条
状态0的有2条
-------
有3名用户已绑定邮箱
-------
队列中的条目数量：19
-------
Total used space is: 0.035 MB


自己的大腿:
admin-run

时间从来不回答:
已执行一次全局观察

自己的大腿:
admin-status

时间从来不回答:
现有3条记录观察中
状态1的有1条
状态0的有2条
-------
有3名用户已绑定邮箱
-------
队列中的条目数量：22
-------
Total used space is: 0.035 MB

```

队列中已积累19条待观察目标，但  article_checker 未去执行观察。

既然 管理员命令可读取到队列状态，可知队列对象**存在**和**访问**正常。切 admin-run 之后新增3条，说明 queue put 正常。
但 article checker 对其使用异常。这个现象在之前没发生过。

准备回退 #73 的修改

**Comment by MamaShip** [comment]
好像也不对，是在 article 3 get 之后卡住了，咬死在这里了

article 3 的文章是：https://mp.weixin.qq.com/s/5Aiyptt6lSApG6S8onRltg

**Comment by MamaShip** [comment]
@ChenliangLi205 看看能找到原因不

**Comment by MamaShip** [comment]
> save file done: /var/wx/article/202006/2.docx
> article 2 get
> article 2 exist
> article 2 get
> article 2 exist
> article 2 get
> article 2 exist
> article 2 get
> article 2 exist
> article 2 get
> article 2 exist
> article 2 get
> article 2 exist
> article 2 get
> article 2 exist
> article 2 get
> article 2 exist
> article 2 get
> article 2 exist
> article 3 get
> connecting ...
> (220, b'smtp.gmail.com ESMTP p189sm6985852pfb.217 - gsmtp')
> loginning ...
> connecting ...
> (220, b'smtp.gmail.com ESMTP s10sm6471666pjl.41 - gsmtp')
> loginning ...
> ^C^CException ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
>     t.join()
>   File "/usr/lib/python3.6/threading.py", line 1056, in join
>     self._wait_for_tstate_lock()
>   File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
>     elif lock.acquire(block, timeout):
> KeyboardInterrupt

**Comment by MamaShip** [comment]
原因是图片无法下载时， request.get() 无限占用线程执行，既不完成也不失败（抛异常）

solution：

添加了 timeout 参数，确保一段时间无法成功下载时，程序仍能向后执行
